# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PRIMI.TV
email: contact@primi.tv
description: PRIMI.TV makes digital products.
baseurl: ""
url: "http://primi.tv/" 
github_username:  Elbone

# Build settings
markdown: kramdown
sass:
  style: compressed
